### ISSUE TITLE
chrome应用商店不能下载

### ISSUE THREAD

**Issue by leotian** [ohsc/ThunderLixianAssistant#10]
chrome上不能下载了吗，显示
程序包无效。详细信息：“无法为内容脚本加载 JavaScript“ThunderLixianExporter/ThunderLixianExporter.user.js”。”。

**Comment by accjiyun** [comment]
Package is invalid. Details: 'Could not load javascript 'ThunderLixianExporter/ThunderLixianExporter.user.js' for content script.'.
@ohsc I have the same problem.

**Comment by ohsc** [comment]
fixed
