### ISSUE TITLE
Set options button to turn grey

### ISSUE THREAD

**Issue by wolfishor** [ohsc/ThunderLixianAssistant#11]
Set options button to turn grey
设置按钮变灰

**Comment by walkingway** [comment]
同问，不能设置 option 按钮是灰色的，chrome 版本是 53

**Comment by beankin** [comment]
chrome版本53，设置按钮直接从右上角消失了

**Comment by ideepblue** [comment]
同样找不到设置按钮 Chrome 53

**Comment by sunetic** [comment]
同样找不到设置，chrome  53.0.2785.143 (64-bit)

**Comment by binux** [comment]
请升级上游版本

**Comment by iabtech** [comment]
我升级了 但还是没有设置按钮

**Comment by Caixiaopig** [comment]
@binux 谢谢，升级后可以了。不知道这个项目何时能整合进去。

**Comment by binux** [comment]
@Caixiaopig 整合很简单 submodule pull 一下就好了，但是我没法打包啊。。。

**Comment by TshineZheng** [comment]
@iabtech @Caixiaopig @binux 请问下在哪升级，是us版吗？那个虽然有齿轮可是无法设置rpc

**Comment by lianghimself** [comment]
啊哈

**Comment by daysofcandy** [comment]
Chrome 54，同样问题，右上角没有设置的齿轮了
请问有谁解决了的吗

**Comment by lianghimself** [comment]
这项目还有人维护吗

**Comment by ohsc** [comment]
已升级
