### ISSUE TITLE
从迅雷导出到Yaaw的时候出现"error http response header was bad or unexpected"。

### ISSUE THREAD

**Issue by Zhgong** [ohsc/ThunderLixianAssistant#8]
但是昨天我使用的时候发现一个问题。从迅雷导出到Yaaw的时候发现会一直出现"error http response header was bad or unexpected"。后来发现是导出的cookie的问题。迅雷离线导出的cookie不完整导致。
可否请作者修复一下？

**Comment by kenshinji** [comment]
居然发现你在这里提issue~

**Comment by Zhgong** [comment]
前天发现这个工具没法用了，你也一直在用这个工具？

2015-07-13 3:06 GMT+02:00 kenshinji <notifications@github.com>:

**Comment by kenshinji** [comment]
没呢，我只是很久以前watch了这个repo，结果今早就发现你在提issue了

**Comment by Zhgong** [comment]
你最近在做啥呢？专于工作还是在自己搞项目？

2015-07-13 8:23 GMT+02:00 kenshinji <notifications@github.com>:

**Comment by kkHAIKE** [comment]
好像这个插件已经失效了

**Comment by Zhgong** [comment]
好像也是通过链接生成的头文件不对。应该可以通过插件里面的JavaScript带来修复，但是我不懂这个编程语言。

**Comment by kenshinji** [comment]
@Zhgong 可以学啊，推荐你去
codecademy.com
codeschool.com

**Comment by ohsc** [comment]
已升级
